config/routes.rb
Rails.application.routes.draw do
  root "posts#index", as: "home"

# For getting about.html.erb use "pages" controller with "About" method
  get 'about' => 'pages#about', as:"about"

#resources Should chek all steps of "posts" controller
  resources :posts do 
    resources :comments
    # will check all comments links inside post link
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments

	# Fiels shouldn't be empty, use TRUE for automatical check params
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true, length: {minimum: 15}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
 class CommentsController < ApplicationController
 	# check for autintification
 	#http_basic_authenticate_with name:"admin", password:"1qw2"

 	def create
 		 @post = Post.find(params[:post_id])
 		 @comment = @post.comments.create(comment_params)
 		 redirect_to posts_path
 	end

 private def comment_params
	 		params.require(:comment).permit(:username, :body)
	 	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@about_us = "About us..." 
		@some_text = "Just message."
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# only for autintificated users
	http_basic_authenticate_with name:"admin", password:"1qw2",
		except: [:index, :show]


	def index
		# will show all the posts from db on our main page
		@post = Post.all
	end

	def new
		@post = Post.new
	end

	def show  # will show our article using post :id
		@post = Post.find(params[:id])
	end

	def edit  # will show our article using post :id
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))  # save post into db
			redirect_to @post # redirect to def "show" with post params
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])

		@post.destroy
		redirect_to posts_path
		#@post = Post.all
	end

	def create
		#render plain: params[:post].inspect
		@post = Post.new(post_params)  # use private def function named post_params

		if(@post.save)  # save post into db
			redirect_to @post # redirect to def "show" with post params
		else
			render 'new'
		end
		
	end

	private 
		def post_params  # print those params, wich should insert into db
			params.require(:post).permit(:title, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Simple blog</title>
  </head>
  <body>

   <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand">GS-program</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <span class="nav-link active"><%= link_to "Main page",home_path%></span>
            </li>
            <li class="nav-item">
              <span class="nav-link"><%= link_to "New post",new_post_path%></span>
            </li>
            <li class="nav-item">
              <span class="nav-link"><%= link_to "About us",about_path%></span>
            </li>
          </ul>
          
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        
        </div>

      </div>
    </nav>
    
    <div class="container">
      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/pages/about.html.erb
<h4><%= @about_us %></h4>
<p><%= @some_text %></p>

app/views/posts/edit.html.erb
<h2>Editing post</h2>

<!-- form_for - will generate all the fiels for our page -->
<!-- url: posts_path - will check it on "posts" page -->
<!-- do |f| - zminna cherez yaku vuvodutumytsya polya z form_for -->
<!-- method: :patch - will show all info in our fields -->

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
	
	<!-- cheking errors, and show them -->
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<!-- create fields using f.+field_name using alias-->
	<p>    
		Name: <br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>    
		Article Text: <br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>
	<!-- create button using f.-->
	<p>    
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/index.html.erb
<h1>Main page</h1>
<br>
<% @post.each do |post| %>
	<div class="card">
	  <div class="card-header">
	    <h5 class="card-title"><%= post.title %></h5>
	  </div>
	  <div class="card-body">
	    <p class="card-text"><%= post.body %></p>
	    <p class="card-text"><%= post.created_at %></p>

	    <%= link_to "Read full article...", post_path(post), :class => 'btn btn-secondary'%>
	  </div>
	</div>
	<br>
<% end %>

app/views/posts/new.html.erb
<h2>Create a post</h2>

<!-- form_for - will generate all the fiels for our page -->
<!-- url: posts_path - will check it on "posts" page -->
<!-- do |f| - zminna cherez yaku vuvodutumytsya polya z form_for -->

<%= form_for :post, url: posts_path do |f| %>
	
	<!-- cheking errors, and show them -->
	<% if @post.errors.any? %>
		<% @post.errors.full_messages.each do |msg| %>
			<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

	<!-- create fields using f.+field_name using alias-->
	<p>    
		Name: <br>
		<%= f.text_field(:title, {:class => 'form-control'}) %>
	</p>
	<p>    
		Article Text: <br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>
	<!-- create button using f.-->
	<p>    
		<%= f.submit({:class => 'btn btn-success'}) %>
	</p>
<% end %>

app/views/posts/show.html.erb
<br>
<div class="card">
  <h2 class="card-header"><%= @post.title %></h2>
  <div class="card-body">
    <p class="card-text"><%= @post.body %></p>
  
    <%= link_to "Edit post", edit_post_path(@post), :class => 'btn btn-warning' %>
	<br>
	<hr>
	<%= button_to "Delete this post", post_path(@post), method: :delete , class: "btn btn-danger"%>
  </div>
</div>
<br>
<hr>

<!-- Here go's Show comments block-->
<h2>All Comments</h2>
<%= @post.comments.each do |comment| %>
	<figure>
	  <blockquote class="blockquote">
	    <p><%= comment.body %></p>
	  </blockquote>
	  <figcaption class="blockquote-footer text-muted">
	    <%= comment.username%> 
	    <cite title="Source Title"><%= comment.created_at%></cite>
	  </figcaption>
	</figure> <hr>
<% end %>
<br>
<br>
<!-- Here go's Add comment block-->
<h4>Create a comment</h4>
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>    
		User name: <br>
		<%= f.text_field(:username, {:class => 'form-control'}) %>
	</p>
	<p>    
		Comment Text: <br>
		<%= f.text_area(:body, {:class => 'form-control'}) %>
	</p>
	<p>    
		<%= f.submit("Add comment", {:class => 'btn btn-success'}) %>
	</p>
<% end %>